@BookingHall.Server_HostAddress = http://localhost:5111

POST http://localhost:5111/api/hall
Content-Type: application/json

{
    "Name" : "Зал E",
    "PricePerHour" : "1000",
    "Capacity" : "20",
    "HallItems" : [
        {
            "ServiceId" : "1"
        },
        {
            "ServiceId" : "2"
        }
    ]
}

###
