@BookingHall.Server_HostAddress = http://localhost:5111

POST    http://localhost:5111/api/booking
Content-Type: application/json

{
    "HallId": 2,
    "BookingStart": "2026-10-02T12:00:00",
    "Duration": "02:00:00",
    "BookingItems": [
        {
            "ServiceId" : 1
        },
        {
            "ServiceId" : 2
        }
    ]
}

###
